### PR TITLE
increased column length for id and secret

### LINKED ISSUE #405: Client ID and Client Secret string limits are too short.
My Nextcloud implementation works with OpenID Connect (OIDC) via Keycloak but not with OIDC via Google or Paypal. The two platforms create the same issue when I register the provider:

```
sudo -u www-data php /var/www/nextcloud/occ user_oidc:provider google --clientid="8********************************************.apps.googleusercontent.com" --clientsecret="G**********************************" --discoveryuri="https://accounts.google.com/.well-known/openid-configuration"
```

The command returns this error on my server:

```
In DbalException.php line 71:An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'client_id' at row 1

In ExceptionConverter.php line 114: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'client_id' at row 1

In Exception.php line 26: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'client_id' at row 1

In Statement.php line 92: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'client_id' at row 1
```

The Google client secret has this format: `8********************************************.apps.googleusercontent.com`. Each star represents a unique character. I considered dropping the `.apps.googleusercontent.com` extension, but Google includes the suffix [in their own examples](https://developers.google.com/identity/protocols/oauth2/openid-connect#sendauthrequest): `client_id=424911365001.apps.googleusercontent.com`.

Paypal has the same problem with Client ID. The service also uses a longer Client Secret. So I get more errors with that service.

### PR DESCRIPTION
**Pull request by nc-fkl**
closes #405
Increased column limit to 2048 for client_secret and client_id as there is no specified max length in https://www.rfc-editor.org/rfc/rfc6749

### CODE REVIEW

File: lib/Migration/Version010304Date20231121102449.php [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+		foreach (['user_oidc_providers', 'user_oidc_id4me'] as $tableName) {
+			if ($schema->hasTable($tableName)) {
+				$table = $schema->getTable($tableName);
+				if ($table->hasColumn('client_secret')) {
+					$column = $table->getColumn('client_secret');
+					$column->setLength(2048);
+					$column = $table->getColumn('client_id');
+					$column->setLength(2048);
+					return $schema;
```
Comment (julien-nc) [inline lib/Migration/Version010304Date20231121102449.php:46]: This will return the schema on the first loop iteration so the change won't be made in `user_oidc_id4me`.
You can set a flag here instead (`$schemaChanged = true;`) and then after the loop:
``` php
if ($schemaChanged) {
    return $schema;
}
```

File: lib/Migration/Version00004Date20200428102743.php [hunk 2]
```diff
@@ -37,11 +37,11 @@ public function changeSchema(IOutput $output, Closure $schemaClosure, array $opt
 		]);
 		$table->addColumn('client_id', 'string', [
 			'notnull' => true,
-			'length' => 64,
+			'length' => 2048,
```
Comment (julien-nc) [inline lib/Migration/Version00004Date20200428102743.php:40]: For fresh installations of the app, all the migration steps will run so it's not necessary to change the old one.

**Review by julien-nc — CHANGES_REQUESTED** [review]
Nice!
It would be nice to show the max length in the settings labels and to limit the input fields.

**Comment by julien-nc** [comment]
:ping_pong: :grin:

File: lib/Migration/Version010304Date20231121102449.php (hunk 1 above)
Comment (nc-fkl) [reply lib/Migration/Version010304Date20231121102449.php]: done :)

**Comment by nc-fkl** [comment]
> 🏓 😁

🏓pong

File: lib/Migration/Version010304Date20231121102449.php [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+		foreach (['user_oidc_providers', 'user_oidc_id4me'] as $tableName) {
+			if ($schema->hasTable($tableName)) {
+				$table = $schema->getTable($tableName);
+				if ($table->hasColumn('client_secret')) {
+					$column = $table->getColumn('client_secret');
+					$column->setLength(2048);
+					$column = $table->getColumn('client_id');
+					$column->setLength(2048);
+					$schemaChanged = true;
+				}
```
Comment (julien-nc) [inline lib/Migration/Version010304Date20231121102449.php:46]:
```suggestion
				if ($table->hasColumn('client_secret')) {
					$column = $table->getColumn('client_secret');
					$column->setLength(2048);
					$schemaChanged = true;
				}
				if ($table->hasColumn('client_id')) {
					$column = $table->getColumn('client_id');
					$column->setLength(2048);
					$schemaChanged = true;
				}
```

Also, schemaChanged is not initialized (to false).

**Review by julien-nc — CHANGES_REQUESTED** [review]

File: lib/Migration/Version010304Date20231121102449.php (hunk 3 above)
Comment (julien-nc) [reply lib/Migration/Version010304Date20231121102449.php]: schemaChanged is still not initialized :grin:

**Review by julien-nc — APPROVED** [review]
